version: 2.1
jobs:
  checkout:
    docker:
      - image: circleci/clojure:lein-2.9.1
    steps:
      - checkout
  test:
    docker:
      - image: circleci/clojure:lein-2.9.1
    steps:
      - run:
          name: Run tests
          command: lein test
          no_output_timeout: 1m
  deploy:
    docker:
      - image: circleci/clojure:lein-2.9.1
    steps:
      - run:
          name: Deploy to clojars
          command: lein deploy clojars

workflows:
  version: 2
  build:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
